apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: certificate_auth_data
    server: api_server
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command:  # add path according to the aws-iam-authenticator path, use which aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "add_your_cluster_name"
